controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel1_controller:
      type: velocity_controllers/JointVelocityController
      joint: omni_wheel_joint_1

    wheel2_controller:
      type: velocity_controllers/JointVelocityController
      joint: omni_wheel_joint_2

    wheel3_controller:
      type: velocity_controllers/JointVelocityController
      joint: omni_wheel_joint_3

    wheel4_controller:
      type: velocity_controllers/JointVelocityController
      joint: omni_wheel_joint_4
